import type { Metadata } from "next";
import "./globals.css";
import { inter, manrope } from "../lib/fonts";

export const metadata: Metadata = {
  title: "Welcome to God's Royal Nation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${inter.className} antialiased w-screen`}
      >

        {children}
      </body>
    </html>
  );
}
